name: Generate PDFs
on: [push]

jobs:
  test:
    name: Generate PDFs
    runs-on: Ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt install -y pandoc texlive-latex-extra texlive-latex-recommended texlive-font-utils texlive-fonts-extra curl
      - name: Download pandoc template
        run: |
          mkdir -p ~/.pandoc/templates && curl -o ~/.pandoc/templates/eisvogel.latex https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex
      - name: Checkout summer course sources
        uses: actions/checkout@v1
      - name: Build PDFs
        run: make ebook deadtree
      - name: Artifact the PDFs
        uses: actions/upload-artifact@v2
        with:
          name: summer-course
          path: |
            printable.pdf
            ebook.pdf


